# QTI IPQ Sound Card Support
snd-soc-ipq-objs := ipq.o
snd-soc-ipq-pcm-raw-objs := ipq-pcm-raw.o ipq-pcm-raw-lb-test.o
snd-soc-ipq-lpass-objs := ipq-lpass.o
snd-soc-ipq-lpass-pcm-raw-objs := ipq-lpass-tdm-pcm.o ipq-pcm-raw-lb-test.o

obj-$(CONFIG_SND_SOC_IPQ_ADSS) += ipq.o ipq-adss.o
obj-$(CONFIG_SND_SOC_IPQ_MBOX) += ipq-mbox.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_RAW) += snd-soc-ipq-pcm-raw.o
obj-$(CONFIG_SND_SOC_IPQ_LPASS) += snd-soc-ipq-lpass.o
obj-$(CONFIG_SND_SOC_IPQ_LPASS_PCM_RAW) += snd-soc-ipq-lpass-pcm-raw.o
